apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-monitor-deploy
spec:
  selector:
    matchLabels:
      project: health-monitor
  replicas: 3
  template:
    metadata:
      labels:
        project: health-monitor
    spec:
      containers:
      - name: edge-demo
        imagePullPolicy: always
        image: hrabhijith/edge-demo:v1.0
        ports:
        - containerPort: 5000