apiVersion: v1
kind: Service
metadata:
  name: health-monitor-service
  labels:
    project: health-monitor
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    project: health-monitor